# 03 — Train Emulators (Multi-z): Cluster Profiles

All cluster profile statistics: CGD, CGED, CPP, CTP, CEP, CEEP, CMP, CYP.
Multi-snapshot emulators (z ≤ 0.5, snapshots 415–624).
All models saved to `../models/<PROFILE>_multiz/`.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import matplotlib.cm as cm
import os

from cosmo_hydro_emu.pca import *
from cosmo_hydro_emu.viz import *
from cosmo_hydro_emu.load_hacc import *
from cosmo_hydro_emu.emu import *
from cosmo_hydro_emu.gp import *
from cosmo_hydro_emu.snapshot_utils import SNAPSHOT_IDS, get_snapshot_redshifts

## Configuration

In [2]:
DirIn = '../data/400MPC_RUNS_5SG_2COSMO_PARAM/HAvoCC/'

start_sim_idx = 1
num_sims = 39
exp_variance = 0.999

z_initial = 200

do_train = True

seed_mass_scale = 1e6
vkin_scale = 1e4
eps_scale = 1e1

## Load parameters

In [3]:
fileIn = '../data/FinalDesign.txt'
params_all = np.loadtxt(fileIn, delimiter=",", skiprows=1)
params32 = params_all[start_sim_idx - 1 : start_sim_idx - 1 + num_sims]
params32[:, 2] /= seed_mass_scale
params32[:, 3] /= vkin_scale
params32[:, 4] /= eps_scale

print('params32 shape:', params32.shape)

# Train/test split
test_sim_indices = np.array([3, 11, 19, 27, 35])
train_sim_indices = np.array([i for i in range(num_sims) if i not in test_sim_indices])

params_train = params32[train_sim_indices]
params_test = params32[test_sim_indices]

print(f'Train: {len(train_sim_indices)} sims, Test: {len(test_sim_indices)} sims')

params32 shape: (39, 7)
Train: 34 sims, Test: 5 sims


## Snapshot setup

In [4]:
z_all, a_all = get_snapshot_redshifts(SNAPSHOT_IDS, z_initial=z_initial)

print(f'Number of snapshots: {len(SNAPSHOT_IDS)}')
print(f'Snapshot IDs: {SNAPSHOT_IDS}')
print(f'Redshift range: z = {z_all[-1]:.2f} to {z_all[0]:.2f}')
print(f'Scale factor range: a = {a_all[0]:.3f} to {a_all[-1]:.3f}')

Number of snapshots: 11
Snapshot IDs: [205, 224, 247, 275, 310, 355, 415, 479, 498, 567, 624]
Redshift range: z = 0.00 to 2.00
Scale factor range: a = 0.333 to 1.000


## Load all profile data

In [5]:
from cosmo_hydro_emu.load_hacc import read_profile_all_snaps

PROFILE_CONFIGS = {
    'CGD':  {'file_prefix': 'ClusterGasDensityProfile',         'label': 'Cluster Gas Density'},
    'CGED': {'file_prefix': 'ClusterGasElectronDensityProfile',  'label': 'Cluster Gas Electron Density'},
    'CPP':  {'file_prefix': 'ClusterGasPressureProfile',         'label': 'Cluster Gas Pressure'},
    'CTP':  {'file_prefix': 'ClusterGasTemperatureProfile',      'label': 'Cluster Gas Temperature'},
    'CEP':  {'file_prefix': 'ClusterGasEntropyProfile',          'label': 'Cluster Gas Entropy'},
    'CEEP': {'file_prefix': 'ClusterElectronEntropyProfile',     'label': 'Cluster Electron Entropy'},
    'CMP':  {'file_prefix': 'ClusterGasMetallicityProfile',      'label': 'Cluster Gas Metallicity'},
    'CYP':  {'file_prefix': 'ClusterGasYProfile',                'label': 'Cluster Compton-y (tSZ)'},
}

profile_data = {}
for short_name, config in PROFILE_CONFIGS.items():
    radius, arr = read_profile_all_snaps(DirIn, num_sims, SNAPSHOT_IDS,
                                          config['file_prefix'],
                                          start_sim_idx=start_sim_idx)
    profile_data[short_name] = arr
    print(f"{short_name}: {arr.shape}")

print(f"Radius bins: {radius.shape}")

CGD: (39, 11, 19)
CGED: (39, 11, 19)
CPP: (39, 11, 19)
CTP: (39, 11, 19)
CEP: (39, 11, 19)
CEEP: (39, 11, 19)
CMP: (39, 11, 19)
CYP: (39, 11, 19)
Radius bins: (19,)


## Radius cut

In [6]:
rlim1, rlim2 = mass_conds('CGD')  # same limits for all profiles
rad_cond = np.where((radius > rlim1) & (radius < rlim2))[0]
y_ind_profiles = radius[rad_cond]
print(f"Radius cut: {len(rad_cond)} bins in [{rlim1:.3f}, {rlim2:.3f}]")

Radius cut: 19 bins in [0.015, 2.750]


## Train all profiles

In [ ]:
profile_z_start_idx = 6  # z <= 0.5
z_index_range = np.arange(profile_z_start_idx, len(SNAPSHOT_IDS))
profile_z_all = z_all[profile_z_start_idx:]

profile_models = {}

for short_name, config in PROFILE_CONFIGS.items():
    print(f"\n{'='*60}")
    print(f"Training {short_name}: {config['label']}")
    print(f"{'='*60}")

    arr = profile_data[short_name]
    y_vals = arr[:, :, rad_cond]  # (num_sims, num_snaps, n_bins_cut)

    model_dir = f'../models/{short_name}_multiz/'

    if do_train:
        os.makedirs(model_dir, exist_ok=True)
        do_gp_train_multiple(
            model_dir=model_dir,
            p_train_all=params_train,
            y_vals_all=y_vals[train_sim_indices],
            y_ind_all=y_ind_profiles,
            z_index_range=z_index_range,
            exp_variance=exp_variance
        )

    model_list, data_list = load_model_multiple(
        model_dir=model_dir,
        p_train_all=params_train,
        y_vals_all=y_vals[train_sim_indices],
        y_ind_all=y_ind_profiles,
        z_index_range=z_index_range,
    )

    profile_models[short_name] = (model_list, data_list)
    print(f"  Loaded {len(model_list)} models for {short_name}")


Training CGD: Cluster Gas Density
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:37<00:00,  1.32it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.27685039 0.13290753 0.3002617  0.72648201 0.82648575]
 [2.56110182 3.46787087 1.17191939 2.90720803 1.78109237]
 [4.458669   4.20830148 2.46387537 4.89932259 1.15084493]
 [1.75670513 1.59816544 0.74748805 1.79119221 6.0082047 ]
 [1.37142363 2.557543   6.94909258 3.5264182  2.14342037]
 [4.13151543 1.78832962 5.48420107 2.21249918 1.20799906]
 [2.26334425 2.85214047 0.43255176 2.69993893 2.38044209]
 [1.35531903 3.01756999 1.77936391 4.20454645 6.03713428]]
lamUz
[[1.68805054 1.76748209 1.64960205 2.01503029 1.78839275]]
lamWs
[[4074.98514941 5870.89667716 4838.09436327 4088.37703158 6293.58757491]]
lamWOs
[[818.2209293]]


MCMC sampling: 100%|██████████| 1000/1000 [00:23<00:00, 42.16it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:22<00:00,  2.18it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.40846567 0.4913894  2.75841306 1.3658151  0.52062694]
 [3.11772958 1.96493362 0.99337851 1.3168067  4.24798636]
 [3.28515625 3.73500162 0.58122938 3.80976724 1.61908317]
 [2.43779171 0.26073172 1.70411731 0.45628977 0.19925019]
 [2.39600957 0.56088116 0.74302099 4.65655595 2.57292751]
 [0.28852492 2.89966888 1.97398728 1.29769903 3.26317452]
 [0.29974725 6.73501476 2.91333661 3.05860332 5.36884563]
 [1.14023908 3.67091078 0.92024322 3.18665065 3.48773637]]
lamUz
[[1.50018385 1.4172462  1.70599163 1.45120199 1.62603255]]
lamWs
[[3796.33447386 4261.0737574  3167.42503121 4070.8048506  3345.30634618]]
lamWOs
[[1113.25585212]]


MCMC sampling: 100%|██████████| 1000/1000 [00:17<00:00, 57.94it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:18<00:00,  2.74it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.09218353 1.13050098 0.56256737 0.32542221]
 [2.02975007 6.93025698 2.62407161 2.40067635]
 [4.55159073 1.21139805 1.4235155  2.83400887]
 [2.66051839 3.75671578 1.23889016 1.11570955]
 [0.55149278 6.43289264 2.72876163 5.79468082]
 [1.69355032 0.54108697 2.59793009 2.82787105]
 [2.21737991 3.50073446 3.49622345 2.45169582]
 [3.91741597 4.96579644 1.20098704 2.8789479 ]]
lamUz
[[1.64728601 1.63797628 1.66304233 2.04542306]]
lamWs
[[4108.26962808 3999.24338818 4281.2839477  4366.57144724]]
lamWOs
[[735.53804839]]


MCMC sampling: 100%|██████████| 1000/1000 [00:12<00:00, 80.88it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:17<00:00,  2.80it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.54379928 0.2577505  0.39261644 0.1779906 ]
 [2.45758717 3.6325809  0.60412893 2.15889972]
 [0.80129088 9.30044847 3.40141997 3.04501644]
 [1.50598146 2.47047614 0.58117996 2.18887822]
 [2.10395183 3.19957358 3.19730342 2.15993782]
 [2.47276033 0.50836657 3.29334271 2.6674611 ]
 [3.1387321  7.80166761 2.21799749 7.65001566]
 [3.45983285 8.50635638 3.62612183 0.48927863]]
lamUz
[[1.81204189 1.55277451 1.54973386 1.73757615]]
lamWs
[[4016.87950115 4509.14145559 4019.21546324 4745.56575521]]
lamWOs
[[1551.35314438]]


MCMC sampling: 100%|██████████| 1000/1000 [00:12<00:00, 79.27it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
lamUz
[[5. 5. 5.]]
lamWs
[[100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:13<00:00,  3.80it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.39017006 0.60944275 0.31190962]
 [1.78786675 1.74532408 1.06627304]
 [1.70380179 2.5820592  1.39336115]
 [3.796989   1.89095315 2.69584979]
 [0.60402357 4.31061297 4.56689068]
 [2.04629663 0.31120411 1.65182091]
 [4.92477936 0.78029775 0.41685879]
 [2.3626489  1.84550045 2.08948829]]
lamUz
[[1.71064781 1.83581616 1.72539424]]
lamWs
[[4180.92520929 3138.59923482 4607.98132423]]
lamWOs
[[649.46581137]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGD_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CGD_multiz/
  Loaded 5 models for CGD

Training CGED: Cluster Gas Electron Density
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.21935858  2.31892947  0.31230778  0.87167894  0.12673037  1.01195174
   0.16816935]
 [ 1.10181544  1.74700835  3.08999411  1.46060768  4.33310566  2.36969632
   5.75373728]
 [ 2.26869042  2.55542155  1.70851284  6.02479038  0.38248458  3.71655734
   3.24051839]
 [ 5.19224997  1.63787894  1.3423394   4.51595671  2.29921568  2.76630701
   4.26724608]
 [ 0.11674534  3.64483019  2.7581526   0.8618427   1.32842951  2.12999762
   0.21416058]
 [ 2.37588674  3.68214948  1.83581764  2.46603913  0.49450027  2.1954291
   0.27354795]
 [ 4.27364324  3.08777171  2.62423786  0.44036935  2.52392816  1.83562011
   2.02873196]
 [21.05155354  0.36646284  2.62822753  2.47980682  4.86969086  2.8512985
   2.61850303]]
lamUz
[[1.95768239 1.42301501 1.80503048 1.43889161 1.60845041 1.80680895
  1.83908101]]
lamWs
[[4320.22821292 5287.81879431 5220.64712199 4631.87482258 4979.67502119
  4810.14463362 4134.55305812]]
lamWOs
[[779.35327065]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.12499666  0.21613445  0.29143945  0.4567949   0.25960845  1.4840818 ]
 [ 1.86541686  0.11344423  2.51879329  4.83182713  1.5800851   5.42723563]
 [11.06729468  4.27150066  2.2631775   0.0893272   0.76191807  0.52302665]
 [ 1.71317079  1.71873693  4.03774234  3.19814383  1.53832961  0.42669713]
 [ 1.39242925  1.32396001  8.35119914  0.35747371  2.72254843  1.42052197]
 [ 2.78395621  2.58832694  0.14320114  0.09078149  1.99318036  2.3048456 ]
 [ 8.68858763  0.21759601  1.00623387  2.46028515  1.15783439  2.01660697]
 [ 8.23215876  0.63840105  7.56263426  2.94762678  1.59000632  1.53299519]]
lamUz
[[1.64250232 1.48472954 1.77469514 1.78635728 1.61551725 2.0242443 ]]
lamWs
[[5082.1071114  4362.55765137 4492.82877907 4505.86321128 4460.0693088
  3982.87683781]]
lamWOs
[[434.63031994]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.34611234 0.59903159 0.51590084 0.18186821 0.20203391 0.32506977]
 [4.57432011 2.77150871 8.60280661 0.7373893  2.76634212 2.8644425 ]
 [1.75485643 0.43485796 0.92312563 0.28997478 2.51686107 0.97741916]
 [3.19574674 0.57127106 4.55189994 3.08833227 5.73930369 4.23030013]
 [2.57295194 1.57727826 3.17019426 1.50054    2.43420768 2.69635698]
 [0.35880908 0.64114171 0.36567974 1.85727165 4.54608989 1.04607258]
 [0.37679322 3.39217246 7.14889396 2.51343634 4.05285989 4.49529699]
 [4.10888957 2.69446472 4.89456507 0.90673498 2.28721146 1.01905575]]
lamUz
[[1.51319488 1.32708304 1.34051348 1.57083614 1.60787498 1.97609163]]
lamWs
[[4451.05683013 5101.72591861 4555.74435885 4200.86427618 4875.37723115
  4856.82427398]]
lamWOs
[[471.9653299]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.53420421 0.24210471 1.45865107 0.40620286 0.27662194]
 [3.8694196  0.8292143  2.26615415 1.62470986 1.99603488]
 [2.07371724 1.97438405 3.8960516  0.70872306 1.29316236]
 [2.61309974 6.8961731  2.72662851 0.09463148 4.0103106 ]
 [0.87077619 2.91096313 2.11842979 2.19969309 0.20396576]
 [6.14787285 1.20230417 0.93986928 5.86349256 0.32035524]
 [6.51321255 1.07381882 4.40408878 0.19749023 4.44230122]
 [5.81065875 1.48023412 5.29477826 1.53300939 2.66008106]]
lamUz
[[1.57938276 1.60213145 1.66932212 1.22316484 1.70865737]]
lamWs
[[4366.57144724 4524.81144533 4631.87482258 4336.0365941  4283.41886546]]
lamWOs
[[389.8823018]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.89926933 0.98997387 0.61322113 0.1508808  0.2795046 ]
 [1.36568442 1.17045493 4.73166693 3.44396259 0.80672437]
 [1.57045204 1.26259085 1.13528635 1.48589537 1.64772813]
 [3.64982905 1.08878253 1.38492365 2.17226294 3.00858133]
 [1.56187739 2.31672066 0.29294182 3.72568554 3.71110324]
 [1.39634307 0.90230749 0.13078748 6.66500541 0.20372345]
 [2.41736376 3.42849999 1.96125341 3.61484635 0.61978909]
 [1.37633902 3.96122703 3.29799721 2.46523022 0.25098968]]
lamUz
[[1.46306401 1.3981697  1.53105045 1.52981157 1.78017982]]
lamWs
[[5079.56613538 4884.44221596 4128.98313856 5452.41257794 4432.73253223]]
lamWOs
[[760.91536225]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CGED_multiz/
  Loaded 5 models for CGED

Training CPP: Cluster Gas Pressure
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.89928768  0.95185302  0.31410007  0.12116802  0.325142  ]
 [ 2.22644627  4.90491096  1.20602323  0.61992302  2.66152003]
 [ 4.77284139  1.47711889  2.88312364  4.32097001  1.42736735]
 [ 0.40244206  0.56613969  1.01317446  2.06513575  1.28088241]
 [ 0.31844438  4.5937772  10.54618014  3.08588679  1.0170449 ]
 [ 2.41580152  3.28944145  0.51998815  1.78642894  0.71642182]
 [ 2.94690112  6.32353796  4.6274942   2.15995154  1.8287302 ]
 [ 4.37084458  5.03525958  5.67151599  0.51392306  2.05323742]]
lamUz
[[1.53459015 1.95628442 1.39633912 1.80750147 1.67533389]]
lamWs
[[4450.31230387 5194.08480604 4030.41895935 4932.68334472 3762.71740934]]
lamWOs
[[622.74127231]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[1.11271509 0.32754765 0.20245417 1.02989502]
 [0.73598399 1.96843325 0.1569225  0.16176996]
 [0.94634948 1.17713051 0.48003633 2.58045694]
 [2.54959677 0.31861562 2.29786374 0.66307377]
 [1.22048161 2.20014558 0.96626161 1.02424624]
 [6.14298397 0.18932577 2.78472832 1.29135064]
 [3.09123041 0.34649211 4.7315582  3.31344792]
 [8.21925198 0.26244899 5.53591878 0.14187657]]
lamUz
[[1.4452714  1.45667938 1.78027004 1.49940704]]
lamWs
[[4261.0737574  4759.80692187 3753.60050228 3896.83288758]]
lamWOs
[[769.53887573]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[1.07928328 0.18441193 0.52824726 0.48519712]
 [4.0661661  1.51278723 2.55194038 0.18960072]
 [1.17564093 1.67178309 1.83422781 1.44500392]
 [0.63644811 1.76722606 1.71760718 2.6798321 ]
 [3.11023281 2.18764961 2.01577686 0.50885909]
 [2.17441883 1.23242826 2.61984786 0.9809496 ]
 [1.31987    4.74250744 2.32557537 0.92354467]
 [0.84805182 1.17371816 0.63073176 0.83383432]]
lamUz
[[1.49667735 1.64898991 1.48513851 1.97885204]]
lamWs
[[4298.04460672 4011.8507947  4280.80203555 4995.17875357]]
lamWOs
[[869.33746227]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
lamUz
[[5. 5. 5.]]
lamWs
[[100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.16130835 0.78743684 1.17856588]
 [2.18359076 0.27831046 0.19955204]
 [1.7203475  2.69260678 2.03284069]
 [3.09660866 0.37172112 0.39948149]
 [2.04787904 0.12456388 0.94521256]
 [3.17163959 2.09638233 2.25993208]
 [0.97321529 4.42192788 3.86163321]
 [4.85000437 2.62490624 0.63371393]]
lamUz
[[1.31355598 1.86338491 1.53998328]]
lamWs
[[4137.49992435 3867.55262012 4620.62444513]]
lamWOs
[[392.01016481]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
lamUz
[[5. 5. 5.]]
lamWs
[[100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.28097126 0.26566695 0.43053662]
 [2.07219937 2.63469318 3.19788029]
 [0.2253035  4.38964469 0.07157183]
 [1.97523357 1.84120542 2.74863679]
 [0.26315156 1.61877894 5.90082202]
 [2.89330285 3.26874682 0.13664951]
 [4.73840977 1.86539063 0.72196273]
 [6.33308666 5.62702162 4.34744381]]
lamUz
[[1.45024377 1.67712027 1.30328654]]
lamWs
[[4449.18055773 4443.01276399 3964.83908875]]
lamWOs
[[780.64447169]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CPP_multiz/
  Loaded 5 models for CPP

Training CTP: Cluster Gas Temperature
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 1.78207995  0.5120302   0.22062394  1.81821843  1.4942083   0.28455241
   0.18153259  0.12364936  1.05292766  0.2349857 ]
 [ 1.21224991  4.06399187  1.53670788  1.77512751  3.1719222   0.16709187
   0.24574296  0.54691063 10.38079388  0.38014159]
 [ 4.05912758  0.47135144  4.73120743  1.81818897  2.28098351  2.9277618
   2.39650234  0.4960395   3.7212223   0.31543048]
 [ 0.58094494  1.2010862   3.93927984  0.99494055  0.11350567  0.73810594
   0.43090701  2.77315615  2.13635663  0.4539998 ]
 [ 1.94361174  0.62908769  1.09782413  2.56146114  2.22151362  2.02576398
   1.82963472  0.80668737  0.71568473  1.69729816]
 [ 2.78480748  1.05758647  0.312678    2.60840445  0.10868173  6.32876583
   4.03087112  1.68980755  0.99371847  2.52380222]
 [ 2.442332    2.28975639  1.3343678   3.10363782  2.02827968  1.29795177
   3.19253961  2.38025231  1.20800057  3.40631432]
 [ 5.74248308  1.50033552  2.0284709   1.44699029  4.55285435  5.69004095

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CTP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CTP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning:  66%|██████▌   | 33/50 [00:34<00:17,  1.04s/it]

## Validation at z=0 (all profiles)

In [ ]:
n_profiles = len(PROFILE_CONFIGS)
ncols = 4
nrows = (n_profiles + ncols - 1) // ncols

fig, axes = plt.subplots(nrows, ncols, figsize=(4*ncols, 3*nrows))
axes = axes.flatten()

for idx, (short_name, config) in enumerate(PROFILE_CONFIGS.items()):
    ax = axes[idx]
    model_list, data_list = profile_models[short_name]
    arr = profile_data[short_name]
    y_vals = arr[:, :, rad_cond]

    for t_idx in test_sim_indices[:3]:
        target = y_vals[t_idx, -1, :]  # z=0 (last snapshot)
        pred_mean, pred_quant = emulate(model_list[-1], params32[t_idx])
        ax.plot(y_ind_profiles, target, 'k-', alpha=0.5)
        ax.plot(y_ind_profiles, pred_mean[:, 0], 'r--', alpha=0.7)

    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_title(short_name)
    ax.set_xlabel(r'$r/R_{500c}$')

for idx in range(len(PROFILE_CONFIGS), len(axes)):
    axes[idx].set_visible(False)

plt.tight_layout()
plt.savefig('../plots/profiles_multiz_validation.png', bbox_inches='tight')

## Redshift interpolation test

In [ ]:
fig, axes = plt.subplots(2, 4, figsize=(16, 6))
axes = axes.flatten()

test_params = params32[test_sim_indices[0]]
z_grid = np.linspace(profile_z_all[-2], profile_z_all[1], 5)

for idx, (short_name, config) in enumerate(PROFILE_CONFIGS.items()):
    ax = axes[idx]
    model_list, data_list = profile_models[short_name]

    for z_target in z_grid:
        params_with_z = np.append(test_params, [z_target])[np.newaxis, :]
        pred_z, pred_z_err = emu_redshift(params_with_z, model_list, data_list, profile_z_all)
        ax.plot(y_ind_profiles, pred_z[:, 0], label=f'z={z_target:.2f}')

    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_title(short_name)
    ax.legend(fontsize=6)

plt.tight_layout()
plt.savefig('../plots/profiles_multiz_redshift_interp.png', bbox_inches='tight')