# 03 — Train Emulators (Multi-z): Cluster Profiles

All cluster profile statistics: CGD, CGED, CPP, CTP, CEP, CEEP, CMP, CYP.
Multi-snapshot emulators (z ≤ 0.5, snapshots 415–624).
All models saved to `../models/<PROFILE>_multiz/`.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import matplotlib.cm as cm
import os

from cosmo_hydro_emu.pca import *
from cosmo_hydro_emu.viz import *
from cosmo_hydro_emu.load_hacc import *
from cosmo_hydro_emu.emu import *
from cosmo_hydro_emu.gp import *
from cosmo_hydro_emu.snapshot_utils import SNAPSHOT_IDS, get_snapshot_redshifts

## Configuration

In [ ]:
DirIn = '../data/400MPC_RUNS_5SG_2COSMO_PARAM/HAvoCC/'

start_sim_idx = 1
num_sims = 39
exp_variance = 0.999

z_initial = 200

do_train = True

seed_mass_scale = 1e6
vkin_scale = 1e4
eps_scale = 1e1

## Load parameters

In [ ]:
fileIn = '../data/FinalDesign.txt'
params_all = np.loadtxt(fileIn, delimiter=",", skiprows=1)
# Design CSV row K corresponds to RUN_K (both 0-indexed); row 0 = RUN000.
# With start_sim_idx=1, num_sims=39 the loaders read RUN001..RUN039; the
# matching slice is rows [1:40] = [start_sim_idx : start_sim_idx + num_sims].
params32 = params_all[start_sim_idx : start_sim_idx + num_sims]
params32[:, 2] /= seed_mass_scale
params32[:, 3] /= vkin_scale
params32[:, 4] /= eps_scale

print('params32 shape:', params32.shape)

# Train/test split
test_sim_indices = np.array([3, 11, 19, 27, 35])
train_sim_indices = np.array([i for i in range(num_sims) if i not in test_sim_indices])

params_train = params32[train_sim_indices]
params_test = params32[test_sim_indices]

print(f'Train: {len(train_sim_indices)} sims, Test: {len(test_sim_indices)} sims')

## Snapshot setup

In [ ]:
z_all, a_all = get_snapshot_redshifts(SNAPSHOT_IDS, z_initial=z_initial)

print(f'Number of snapshots: {len(SNAPSHOT_IDS)}')
print(f'Snapshot IDs: {SNAPSHOT_IDS}')
print(f'Redshift range: z = {z_all[-1]:.2f} to {z_all[0]:.2f}')
print(f'Scale factor range: a = {a_all[0]:.3f} to {a_all[-1]:.3f}')

Number of snapshots: 11
Snapshot IDs: [205, 224, 247, 275, 310, 355, 415, 479, 498, 567, 624]
Redshift range: z = 0.00 to 2.00
Scale factor range: a = 0.333 to 1.000


## Load all profile data

In [ ]:
from cosmo_hydro_emu.load_hacc import read_profile_all_snaps

PROFILE_CONFIGS = {
    'CGD':  {'file_prefix': 'ClusterGasDensityProfile',         'label': 'Cluster Gas Density'},
    'CGED': {'file_prefix': 'ClusterGasElectronDensityProfile',  'label': 'Cluster Gas Electron Density'},
    'CPP':  {'file_prefix': 'ClusterGasPressureProfile',         'label': 'Cluster Gas Pressure'},
    'CTP':  {'file_prefix': 'ClusterGasTemperatureProfile',      'label': 'Cluster Gas Temperature'},
    'CEP':  {'file_prefix': 'ClusterGasEntropyProfile',          'label': 'Cluster Gas Entropy'},
    'CEEP': {'file_prefix': 'ClusterElectronEntropyProfile',     'label': 'Cluster Electron Entropy'},
    'CMP':  {'file_prefix': 'ClusterGasMetallicityProfile',      'label': 'Cluster Gas Metallicity'},
    'CYP':  {'file_prefix': 'ClusterGasYProfile',                'label': 'Cluster Compton-y (tSZ)'},
}

profile_data = {}
for short_name, config in PROFILE_CONFIGS.items():
    radius, arr = read_profile_all_snaps(DirIn, num_sims, SNAPSHOT_IDS,
                                          config['file_prefix'],
                                          start_sim_idx=start_sim_idx)
    profile_data[short_name] = arr
    print(f"{short_name}: {arr.shape}")

print(f"Radius bins: {radius.shape}")

CGD: (39, 11, 19)
CGED: (39, 11, 19)
CPP: (39, 11, 19)
CTP: (39, 11, 19)
CEP: (39, 11, 19)
CEEP: (39, 11, 19)
CMP: (39, 11, 19)
CYP: (39, 11, 19)
Radius bins: (19,)


## Radius cut

In [ ]:
rlim1, rlim2 = mass_conds('CGD')  # same limits for all profiles
rad_cond = np.where((radius > rlim1) & (radius < rlim2))[0]
y_ind_profiles = radius[rad_cond]
print(f"Radius cut: {len(rad_cond)} bins in [{rlim1:.3f}, {rlim2:.3f}]")

Radius cut: 19 bins in [0.015, 2.750]


## Train all profiles

In [ ]:
profile_z_start_idx = 6  # z <= 0.5
z_index_range = np.arange(profile_z_start_idx, len(SNAPSHOT_IDS))
profile_z_all = z_all[profile_z_start_idx:]

profile_models = {}

for short_name, config in PROFILE_CONFIGS.items():
    print(f"\n{'='*60}")
    print(f"Training {short_name}: {config['label']}")
    print(f"{'='*60}")

    arr = profile_data[short_name]
    y_vals = arr[:, :, rad_cond]  # (num_sims, num_snaps, n_bins_cut)

    model_dir = f'../models/{short_name}_multiz/'

    if do_train:
        os.makedirs(model_dir, exist_ok=True)
        do_gp_train_multiple(
            model_dir=model_dir,
            p_train_all=params_train,
            y_vals_all=y_vals[train_sim_indices],
            y_ind_all=y_ind_profiles,
            z_index_range=z_index_range,
            exp_variance=exp_variance
        )

    model_list, data_list = load_model_multiple(
        model_dir=model_dir,
        p_train_all=params_train,
        y_vals_all=y_vals[train_sim_indices],
        y_ind_all=y_ind_profiles,
        z_index_range=z_index_range,
    )

    profile_models[short_name] = (model_list, data_list)
    print(f"  Loaded {len(model_list)} models for {short_name}")


Training CGD: Cluster Gas Density
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:37<00:00,  1.32it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.27685039 0.13290753 0.3002617  0.72648201 0.82648575]
 [2.56110182 3.46787087 1.17191939 2.90720803 1.78109237]
 [4.458669   4.20830148 2.46387537 4.89932259 1.15084493]
 [1.75670513 1.59816544 0.74748805 1.79119221 6.0082047 ]
 [1.37142363 2.557543   6.94909258 3.5264182  2.14342037]
 [4.13151543 1.78832962 5.48420107 2.21249918 1.20799906]
 [2.26334425 2.85214047 0.43255176 2.69993893 2.38044209]
 [1.35531903 3.01756999 1.77936391 4.20454645 6.03713428]]
lamUz
[[1.68805054 1.76748209 1.64960205 2.01503029 1.78839275]]
lamWs
[[4074.98514941 5870.89667716 4838.09436327 4088.37703158 6293.58757491]]
lamWOs
[[818.2209293]]


MCMC sampling: 100%|██████████| 1000/1000 [00:23<00:00, 42.16it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:22<00:00,  2.18it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.40846567 0.4913894  2.75841306 1.3658151  0.52062694]
 [3.11772958 1.96493362 0.99337851 1.3168067  4.24798636]
 [3.28515625 3.73500162 0.58122938 3.80976724 1.61908317]
 [2.43779171 0.26073172 1.70411731 0.45628977 0.19925019]
 [2.39600957 0.56088116 0.74302099 4.65655595 2.57292751]
 [0.28852492 2.89966888 1.97398728 1.29769903 3.26317452]
 [0.29974725 6.73501476 2.91333661 3.05860332 5.36884563]
 [1.14023908 3.67091078 0.92024322 3.18665065 3.48773637]]
lamUz
[[1.50018385 1.4172462  1.70599163 1.45120199 1.62603255]]
lamWs
[[3796.33447386 4261.0737574  3167.42503121 4070.8048506  3345.30634618]]
lamWOs
[[1113.25585212]]


MCMC sampling: 100%|██████████| 1000/1000 [00:17<00:00, 57.94it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:18<00:00,  2.74it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.09218353 1.13050098 0.56256737 0.32542221]
 [2.02975007 6.93025698 2.62407161 2.40067635]
 [4.55159073 1.21139805 1.4235155  2.83400887]
 [2.66051839 3.75671578 1.23889016 1.11570955]
 [0.55149278 6.43289264 2.72876163 5.79468082]
 [1.69355032 0.54108697 2.59793009 2.82787105]
 [2.21737991 3.50073446 3.49622345 2.45169582]
 [3.91741597 4.96579644 1.20098704 2.8789479 ]]
lamUz
[[1.64728601 1.63797628 1.66304233 2.04542306]]
lamWs
[[4108.26962808 3999.24338818 4281.2839477  4366.57144724]]
lamWOs
[[735.53804839]]


MCMC sampling: 100%|██████████| 1000/1000 [00:12<00:00, 80.88it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:17<00:00,  2.80it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.54379928 0.2577505  0.39261644 0.1779906 ]
 [2.45758717 3.6325809  0.60412893 2.15889972]
 [0.80129088 9.30044847 3.40141997 3.04501644]
 [1.50598146 2.47047614 0.58117996 2.18887822]
 [2.10395183 3.19957358 3.19730342 2.15993782]
 [2.47276033 0.50836657 3.29334271 2.6674611 ]
 [3.1387321  7.80166761 2.21799749 7.65001566]
 [3.45983285 8.50635638 3.62612183 0.48927863]]
lamUz
[[1.81204189 1.55277451 1.54973386 1.73757615]]
lamWs
[[4016.87950115 4509.14145559 4019.21546324 4745.56575521]]
lamWOs
[[1551.35314438]]


MCMC sampling: 100%|██████████| 1000/1000 [00:12<00:00, 79.27it/s]


Model saved to ../models/CGD_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
lamUz
[[5. 5. 5.]]
lamWs
[[100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning: 100%|██████████| 50/50 [00:13<00:00,  3.80it/s]


Done with tune_step_size.
Selected step sizes:
betaU
[[0.39017006 0.60944275 0.31190962]
 [1.78786675 1.74532408 1.06627304]
 [1.70380179 2.5820592  1.39336115]
 [3.796989   1.89095315 2.69584979]
 [0.60402357 4.31061297 4.56689068]
 [2.04629663 0.31120411 1.65182091]
 [4.92477936 0.78029775 0.41685879]
 [2.3626489  1.84550045 2.08948829]]
lamUz
[[1.71064781 1.83581616 1.72539424]]
lamWs
[[4180.92520929 3138.59923482 4607.98132423]]
lamWOs
[[649.46581137]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGD_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CGD_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CGD_multiz/
  Loaded 5 models for CGD

Training CGED: Cluster Gas Electron Density
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.21935858  2.31892947  0.31230778  0.87167894  0.12673037  1.01195174
   0.16816935]
 [ 1.10181544  1.74700835  3.08999411  1.46060768  4.33310566  2.36969632
   5.75373728]
 [ 2.26869042  2.55542155  1.70851284  6.02479038  0.38248458  3.71655734
   3.24051839]
 [ 5.19224997  1.63787894  1.3423394   4.51595671  2.29921568  2.76630701
   4.26724608]
 [ 0.11674534  3.64483019  2.7581526   0.8618427   1.32842951  2.12999762
   0.21416058]
 [ 2.37588674  3.68214948  1.83581764  2.46603913  0.49450027  2.1954291
   0.27354795]
 [ 4.27364324  3.08777171  2.62423786  0.44036935  2.52392816  1.83562011
   2.02873196]
 [21.05155354  0.36646284  2.62822753  2.47980682  4.86969086  2.8512985
   2.61850303]]
lamUz
[[1.95768239 1.42301501 1.80503048 1.43889161 1.60845041 1.80680895
  1.83908101]]
lamWs
[[4320.22821292 5287.81879431 5220.64712199 4631.87482258 4979.67502119
  4810.14463362 4134.55305812]]
lamWOs
[[779.35327065]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.12499666  0.21613445  0.29143945  0.4567949   0.25960845  1.4840818 ]
 [ 1.86541686  0.11344423  2.51879329  4.83182713  1.5800851   5.42723563]
 [11.06729468  4.27150066  2.2631775   0.0893272   0.76191807  0.52302665]
 [ 1.71317079  1.71873693  4.03774234  3.19814383  1.53832961  0.42669713]
 [ 1.39242925  1.32396001  8.35119914  0.35747371  2.72254843  1.42052197]
 [ 2.78395621  2.58832694  0.14320114  0.09078149  1.99318036  2.3048456 ]
 [ 8.68858763  0.21759601  1.00623387  2.46028515  1.15783439  2.01660697]
 [ 8.23215876  0.63840105  7.56263426  2.94762678  1.59000632  1.53299519]]
lamUz
[[1.64250232 1.48472954 1.77469514 1.78635728 1.61551725 2.0242443 ]]
lamWs
[[5082.1071114  4362.55765137 4492.82877907 4505.86321128 4460.0693088
  3982.87683781]]
lamWOs
[[434.63031994]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.34611234 0.59903159 0.51590084 0.18186821 0.20203391 0.32506977]
 [4.57432011 2.77150871 8.60280661 0.7373893  2.76634212 2.8644425 ]
 [1.75485643 0.43485796 0.92312563 0.28997478 2.51686107 0.97741916]
 [3.19574674 0.57127106 4.55189994 3.08833227 5.73930369 4.23030013]
 [2.57295194 1.57727826 3.17019426 1.50054    2.43420768 2.69635698]
 [0.35880908 0.64114171 0.36567974 1.85727165 4.54608989 1.04607258]
 [0.37679322 3.39217246 7.14889396 2.51343634 4.05285989 4.49529699]
 [4.10888957 2.69446472 4.89456507 0.90673498 2.28721146 1.01905575]]
lamUz
[[1.51319488 1.32708304 1.34051348 1.57083614 1.60787498 1.97609163]]
lamWs
[[4451.05683013 5101.72591861 4555.74435885 4200.86427618 4875.37723115
  4856.82427398]]
lamWOs
[[471.9653299]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.53420421 0.24210471 1.45865107 0.40620286 0.27662194]
 [3.8694196  0.8292143  2.26615415 1.62470986 1.99603488]
 [2.07371724 1.97438405 3.8960516  0.70872306 1.29316236]
 [2.61309974 6.8961731  2.72662851 0.09463148 4.0103106 ]
 [0.87077619 2.91096313 2.11842979 2.19969309 0.20396576]
 [6.14787285 1.20230417 0.93986928 5.86349256 0.32035524]
 [6.51321255 1.07381882 4.40408878 0.19749023 4.44230122]
 [5.81065875 1.48023412 5.29477826 1.53300939 2.66008106]]
lamUz
[[1.57938276 1.60213145 1.66932212 1.22316484 1.70865737]]
lamWs
[[4366.57144724 4524.81144533 4631.87482258 4336.0365941  4283.41886546]]
lamWOs
[[389.8823018]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.89926933 0.98997387 0.61322113 0.1508808  0.2795046 ]
 [1.36568442 1.17045493 4.73166693 3.44396259 0.80672437]
 [1.57045204 1.26259085 1.13528635 1.48589537 1.64772813]
 [3.64982905 1.08878253 1.38492365 2.17226294 3.00858133]
 [1.56187739 2.31672066 0.29294182 3.72568554 3.71110324]
 [1.39634307 0.90230749 0.13078748 6.66500541 0.20372345]
 [2.41736376 3.42849999 1.96125341 3.61484635 0.61978909]
 [1.37633902 3.96122703 3.29799721 2.46523022 0.25098968]]
lamUz
[[1.46306401 1.3981697  1.53105045 1.52981157 1.78017982]]
lamWs
[[5079.56613538 4884.44221596 4128.98313856 5452.41257794 4432.73253223]]
lamWOs
[[760.91536225]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CGED_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CGED_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CGED_multiz/
  Loaded 5 models for CGED

Training CPP: Cluster Gas Pressure
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.89928768  0.95185302  0.31410007  0.12116802  0.325142  ]
 [ 2.22644627  4.90491096  1.20602323  0.61992302  2.66152003]
 [ 4.77284139  1.47711889  2.88312364  4.32097001  1.42736735]
 [ 0.40244206  0.56613969  1.01317446  2.06513575  1.28088241]
 [ 0.31844438  4.5937772  10.54618014  3.08588679  1.0170449 ]
 [ 2.41580152  3.28944145  0.51998815  1.78642894  0.71642182]
 [ 2.94690112  6.32353796  4.6274942   2.15995154  1.8287302 ]
 [ 4.37084458  5.03525958  5.67151599  0.51392306  2.05323742]]
lamUz
[[1.53459015 1.95628442 1.39633912 1.80750147 1.67533389]]
lamWs
[[4450.31230387 5194.08480604 4030.41895935 4932.68334472 3762.71740934]]
lamWOs
[[622.74127231]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[1.11271509 0.32754765 0.20245417 1.02989502]
 [0.73598399 1.96843325 0.1569225  0.16176996]
 [0.94634948 1.17713051 0.48003633 2.58045694]
 [2.54959677 0.31861562 2.29786374 0.66307377]
 [1.22048161 2.20014558 0.96626161 1.02424624]
 [6.14298397 0.18932577 2.78472832 1.29135064]
 [3.09123041 0.34649211 4.7315582  3.31344792]
 [8.21925198 0.26244899 5.53591878 0.14187657]]
lamUz
[[1.4452714  1.45667938 1.78027004 1.49940704]]
lamWs
[[4261.0737574  4759.80692187 3753.60050228 3896.83288758]]
lamWOs
[[769.53887573]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[1.07928328 0.18441193 0.52824726 0.48519712]
 [4.0661661  1.51278723 2.55194038 0.18960072]
 [1.17564093 1.67178309 1.83422781 1.44500392]
 [0.63644811 1.76722606 1.71760718 2.6798321 ]
 [3.11023281 2.18764961 2.01577686 0.50885909]
 [2.17441883 1.23242826 2.61984786 0.9809496 ]
 [1.31987    4.74250744 2.32557537 0.92354467]
 [0.84805182 1.17371816 0.63073176 0.83383432]]
lamUz
[[1.49667735 1.64898991 1.48513851 1.97885204]]
lamWs
[[4298.04460672 4011.8507947  4280.80203555 4995.17875357]]
lamWOs
[[869.33746227]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
lamUz
[[5. 5. 5.]]
lamWs
[[100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.16130835 0.78743684 1.17856588]
 [2.18359076 0.27831046 0.19955204]
 [1.7203475  2.69260678 2.03284069]
 [3.09660866 0.37172112 0.39948149]
 [2.04787904 0.12456388 0.94521256]
 [3.17163959 2.09638233 2.25993208]
 [0.97321529 4.42192788 3.86163321]
 [4.85000437 2.62490624 0.63371393]]
lamUz
[[1.31355598 1.86338491 1.53998328]]
lamWs
[[4137.49992435 3867.55262012 4620.62444513]]
lamWOs
[[392.01016481]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
lamUz
[[5. 5. 5.]]
lamWs
[[100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.28097126 0.26566695 0.43053662]
 [2.07219937 2.63469318 3.19788029]
 [0.2253035  4.38964469 0.07157183]
 [1.97523357 1.84120542 2.74863679]
 [0.26315156 1.61877894 5.90082202]
 [2.89330285 3.26874682 0.13664951]
 [4.73840977 1.86539063 0.72196273]
 [6.33308666 5.62702162 4.34744381]]
lamUz
[[1.45024377 1.67712027 1.30328654]]
lamWs
[[4449.18055773 4443.01276399 3964.83908875]]
lamWOs
[[780.64447169]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CPP_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CPP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CPP_multiz/
  Loaded 5 models for CPP

Training CTP: Cluster Gas Temperature
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 1.78207995  0.5120302   0.22062394  1.81821843  1.4942083   0.28455241
   0.18153259  0.12364936  1.05292766  0.2349857 ]
 [ 1.21224991  4.06399187  1.53670788  1.77512751  3.1719222   0.16709187
   0.24574296  0.54691063 10.38079388  0.38014159]
 [ 4.05912758  0.47135144  4.73120743  1.81818897  2.28098351  2.9277618
   2.39650234  0.4960395   3.7212223   0.31543048]
 [ 0.58094494  1.2010862   3.93927984  0.99494055  0.11350567  0.73810594
   0.43090701  2.77315615  2.13635663  0.4539998 ]
 [ 1.94361174  0.62908769  1.09782413  2.56146114  2.22151362  2.02576398
   1.82963472  0.80668737  0.71568473  1.69729816]
 [ 2.78480748  1.05758647  0.312678    2.60840445  0.10868173  6.32876583
   4.03087112  1.68980755  0.99371847  2.52380222]
 [ 2.442332    2.28975639  1.3343678   3.10363782  2.02827968  1.29795177
   3.19253961  2.38025231  1.20800057  3.40631432]
 [ 5.74248308  1.50033552  2.0284709   1.44699029  4.55285435  5.69004095

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CTP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CTP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.15886528 0.29263158 0.57691181 0.70482769 0.1359554  0.15703876
  0.44788085 0.582495   2.06558645 0.93530497]
 [0.89256798 3.64930672 2.18244062 1.75543927 1.40585288 3.51986786
  0.70762741 2.81764341 0.19375636 2.30137759]
 [2.90238547 0.93159431 1.97891407 1.07786797 3.84916478 1.35291613
  2.14797791 0.71775964 2.42026116 3.28089582]
 [2.69752657 0.37497079 4.11936464 2.97591606 1.76502403 0.38815617
  0.55024874 1.21131423 0.47256399 1.89556136]
 [0.66965844 0.73448085 2.42840124 2.38257667 1.59940904 0.65232133
  3.34411633 1.78554234 0.43122149 0.39904588]
 [6.19873736 0.42456135 0.72375283 2.62691451 2.84709582 0.39637463
  1.35956088 2.87711268 1.39571695 1.66420597]
 [1.85852554 1.90113023 3.83265051 3.48169551 3.29674336 2.26101302
  2.81193813 3.06521568 1.76977429 0.947601  ]
 [3.18922812 2.11829952 1.98615313 6.46868144 1.88869359 1.55002583
  0.62958439 0.5991303  2.41609897 1.0064256 ]]
lamUz
[[1.45876061 1.70391

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CTP_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CTP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.47986723 0.24727147 0.68064242 0.34820004 0.32452351 2.30468788
  0.62456405 0.81002102 0.36974576 0.38476004]
 [0.23045351 0.48312023 1.8753652  4.80242245 0.3357982  0.12613841
  2.3249524  2.29782829 0.7919684  1.44076375]
 [4.20018132 0.45522158 1.16227796 3.21615915 2.79739122 0.14630035
  0.4860068  0.79214292 3.56570339 2.45926354]
 [1.64182969 5.45275177 2.05010901 1.09515798 2.48326376 2.51693448
  2.62908382 2.02359187 1.44285829 3.17984068]
 [0.34403384 4.63557765 1.60851444 2.65471632 1.25340576 0.46715809
  1.47895561 2.33589925 0.28515519 3.7182694 ]
 [3.38739318 2.13663206 2.13574085 2.55527575 0.07931963 0.29236207
  2.21760473 2.09549056 2.76539075 1.96216226]
 [2.03361847 0.70117708 0.95247988 1.49597833 0.70980144 2.83855413
  2.05516497 1.83206582 3.22585599 0.45736553]
 [5.84001064 2.77133699 2.71935103 0.66528038 1.46853819 2.36826489
  2.30127602 0.692355   2.28395259 1.13748708]]
lamUz
[[1.57086347 1.43100

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CTP_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CTP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 1.37179411  0.30959218  0.14877963  0.4029402   1.61574052  1.50881503
   0.51714095  0.35169478]
 [ 1.92489761  1.51816912  3.30657658  1.89067329  4.02022672  0.21806361
   0.21399072  2.00608868]
 [ 2.06357017  2.88799881  2.033632    1.98309126  0.70501566  4.58265606
   2.3036155   0.05391684]
 [ 0.76619755  3.21783786  1.07362524  0.30320507  5.88695362  0.51837774
   2.38460712  0.85874352]
 [ 2.56464312  4.02482528  2.84237101  0.68825509  1.03079198  0.46125435
   0.15948456  1.91166893]
 [ 1.87753141  2.55429643  1.82731987  0.13973048  2.40650249  2.86146744
   1.06638858  0.27649601]
 [ 8.4755534   1.13676873  1.07105916  0.266796    1.06231753  3.5848784
   0.70888199  1.49338235]
 [13.71441554  0.86555943  0.49420432  2.86022488  2.90772804  2.10912149
   1.38738012  0.07459652]]
lamUz
[[1.67161509 1.59608664 1.64089561 1.54642478 1.87858371 2.08863693
  1.86815412 1.93648461]]
lamWs
[[5247.34325327 3824.13363599 372

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CTP_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CTP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.36398647 0.35555815 1.04560832 0.39243952 0.10925481 0.62374455
  0.36791282]
 [0.63701141 0.21050952 1.35358764 2.11290852 0.12527551 1.63293128
  1.04514755]
 [2.31825852 0.85733977 0.73999748 3.13841143 2.34375397 2.23413814
  1.92973775]
 [3.27762933 3.1895146  1.61757895 1.09751885 2.13785071 1.85116707
  2.23676862]
 [0.9100344  2.19115875 1.71386476 1.62414372 1.67086142 0.58961457
  1.66291284]
 [3.85956737 2.82770886 1.95056989 0.7360977  0.9787162  1.95961571
  0.57094989]
 [1.29465577 2.09660503 1.11747436 0.90620254 0.17448533 1.04847789
  4.91174554]
 [3.92736175 3.65792746 1.73454942 3.49878795 0.6998433  1.61006235
  0.32242811]]
lamUz
[[1.56866443 1.26598852 1.64050885 1.92329903 1.55448144 1.9693466
  1.78774485]]
lamWs
[[5167.60448147 4947.58108937 4108.56414938 4711.60791661 4159.65522254
  4698.30439195 4487.04317055]]
lamWOs
[[479.48026731]]


Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CTP_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CTP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CTP_multiz/
  Loaded 5 models for CTP

Training CEP: Cluster Gas Entropy
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.19346641  0.79192553  0.87086046  1.45853024  1.04236328  0.19937542
   1.39295125  0.56407672  1.41726203  0.28766033]
 [ 0.16604668  2.33011641  3.05915859  1.02741224  1.0152453   0.87903291
   0.93045937  0.88765377  2.37023045  1.0449343 ]
 [ 3.5281325   3.28982101  3.45788368  0.758103    4.42424124  1.65012275
   2.12425478  1.63299632  2.61795188  3.25099997]
 [ 0.09025419  5.38740107  3.13849482  2.56322452  1.63703076  0.15387675
   2.77913765  2.75494249  3.18423345  3.521988  ]
 [ 0.83863704  1.33265608  0.13605779  0.59985548  0.9583296   1.91354181
   0.96519123  0.64776577  1.72652879  0.78969203]
 [ 2.61684015  4.51445913  0.9961232   5.46696601  2.43310849  2.30644739
   1.4498966   1.46987065  0.59605784  3.77844599]
 [ 0.10508983  2.24493541  6.08501277  3.45829041  4.28036561  4.47343682
   2.20268076  5.63783234  1.12450136  3.34959878]
 [ 0.58710714 15.95396719  0.12486553  2.62339478  0.54796691  0.3079755

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.46378336 0.19453459 0.35532429 0.32337522 0.70992449 0.22858969
  0.57081182 0.46577391]
 [0.73707288 0.63018145 4.3713636  0.62910176 3.8645736  1.06417433
  2.17988616 1.19834823]
 [6.03377476 3.69538408 0.81398299 4.8154178  2.95708421 5.1481634
  2.12012704 1.49422731]
 [0.74090008 7.97477649 1.91648574 3.09874199 1.89758107 0.89453633
  1.09798717 3.69369985]
 [1.59793142 0.62768944 1.10923073 0.80317897 1.85761    1.13497615
  0.50900957 1.9170335 ]
 [1.743843   2.56280037 2.18269798 1.86556819 0.14892837 4.15867324
  2.51720043 1.50134656]
 [1.58280003 2.45879339 5.66194875 5.28779104 0.14223283 2.14222402
  0.06905983 2.26669967]
 [2.72990339 2.48125197 3.837472   2.75730804 1.41348864 2.3806632
  2.11587501 3.06232615]]
lamUz
[[1.71659563 1.38357427 1.61774627 1.49775991 1.72335683 1.66614857
  1.70660504 2.08713191]]
lamWs
[[4475.91506232 4711.32460954 3873.66987335 4989.84313583 6345.13492264
  3671.64210808 4128.20205

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEP_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.52566876  0.42003108  0.36935471  1.19820097  0.17068835  0.73605184
   0.48870261  0.23753787  0.22539194]
 [ 0.41382328  2.81409066  2.86609685  4.13735124  0.62152805 12.39982414
   1.24054807  1.94459827  2.51248144]
 [ 2.7224183   3.17225863  2.98751111  5.0609228   1.41748836  1.98484726
   9.83242063  1.14750936  2.64529342]
 [ 0.72805207  0.48870042  2.21924392  9.01070967  0.76310567  2.82367867
   0.62266411  4.57354145  1.39928635]
 [ 1.0368348   9.10420939  0.81336383  2.02199774  1.0707739   2.1141495
   1.16532034  6.17111313  1.90113895]
 [ 1.37645042  0.42620965  3.06609163  1.43386402  0.45137919  0.39516406
   0.65430641  1.7019951   1.49986132]
 [ 1.61460362  0.61850166  2.31475567  2.94137081  1.54362397  0.45232838
   2.62401566  1.73958509  3.66376113]
 [ 0.92107858  2.49762068  1.90101372  1.80485646  3.84204586  0.62665716
   0.50214192  2.40267608  1.39327897]]
lamUz
[[1.37406367 1.55061894 1.87166357 1.

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEP_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.34126627 0.50081691 0.63630979 0.82102418 0.265954   0.15107765
  0.4516322  0.70475363]
 [0.4320178  3.43016506 0.06537513 3.96007663 0.79215296 1.5597883
  4.00501977 1.92642126]
 [1.89361642 1.38071895 1.43667133 1.7639656  2.11867334 2.4728541
  1.63524789 0.26407372]
 [0.24194469 0.6683926  2.17114788 1.60085118 0.0702826  0.8457509
  2.51712099 4.85541351]
 [1.03110462 3.28725259 0.41744246 2.0621078  0.47314989 0.45848167
  0.85852849 2.32917434]
 [1.8743864  4.90408948 1.57767415 1.62647226 5.86004969 1.15734644
  1.32534157 1.31671635]
 [2.5104678  0.4772185  1.72256734 2.19820763 1.05050951 6.56577471
  2.07855871 2.95310853]
 [0.26149481 1.96570874 1.01072827 1.01328394 0.28916981 1.41547087
  3.60875509 0.99916466]]
lamUz
[[1.32922835 1.39807495 1.21806654 1.8512182  1.50373688 1.78767892
  1.87925004 2.32232558]]
lamWs
[[4710.68061262 4558.80911872 4699.62575197 3695.39518232 4457.88968389
  4303.93732119 5137.916495

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEP_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.13997189 0.43956272 0.35309779 0.3923068  0.18548772 0.4643352
  0.69687611 0.52823744 0.3529507 ]
 [0.56132843 2.23784847 3.02840843 1.15437588 2.48274055 0.40672037
  1.15869256 0.22636148 2.17409753]
 [1.39698567 5.64247382 0.67333528 7.58132037 1.4188822  5.14495896
  1.1103323  2.96212249 0.54428788]
 [1.52858495 1.70613678 1.96785564 3.50908781 0.90131289 1.20757174
  2.85909639 1.09411252 2.83320442]
 [2.28118399 1.67179748 6.7057745  1.17812395 3.77990548 2.44070191
  3.93621847 1.95208534 0.15637531]
 [4.6274765  2.66590912 0.06179433 0.99705831 1.43055716 1.29531168
  3.80820634 1.29185927 1.35925674]
 [0.073922   5.23533218 0.08453878 5.56894825 6.92173698 2.46113484
  0.32695652 0.68687176 2.36052279]
 [0.21584138 6.95618829 3.47754361 1.44336302 3.61214076 0.74389303
  1.19729993 0.86456364 0.6025656 ]]
lamUz
[[1.94827394 1.35864834 1.36705243 1.59760222 1.55146085 1.85704627
  1.76509594 1.83447318 2.10830939]]
lamW

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEP_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CEP_multiz/
  Loaded 5 models for CEP

Training CEEP: Cluster Electron Entropy
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.13819203  0.41369772  0.36641682  0.26661046  0.81848105  0.34770699
   0.62469261  0.20499634  0.31529142  0.57729803]
 [ 1.47266749  3.16876005  5.03922867  1.13031964  5.24893291  4.54353641
   0.24451898  0.66376083  1.328466    1.19794848]
 [ 2.65914285  0.95186939  0.35365946  1.03114818  3.93963705  4.40326397
   3.06528703  1.96517815  1.31736329  2.4466644 ]
 [ 1.28021024  4.37210362 11.73408524  5.39668446  1.22469628  2.01396529
   2.81879621  0.85128634  0.4769637   0.43799892]
 [ 0.96069605  0.84135142  2.31754452  2.84559238  3.56288982  3.45485474
   0.64852505  0.82797309  1.33596311  0.29965442]
 [ 1.15896011  2.45684387  0.76742621  3.35396362  6.13301461  1.51190714
   1.35007042  3.05229716  2.37475939  0.07806217]
 [ 0.13171323  7.0924688   0.2933364   0.22040819  0.56830559  4.51276144
   2.4829784   1.67252135  3.93294389  3.35396362]
 [ 0.59429148  3.37149543  2.73013814  3.73522894  0.65345831  0.9373915

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEEP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CEEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.37526528  0.41991769  0.80230984  0.50202687  0.62260336  0.23518889
   0.90494405  0.68365593]
 [ 0.89468847  2.22048974  5.23138798  1.39040132  3.46117742  0.93547621
   0.36437661  0.98381214]
 [ 3.51638112  1.49141399  3.95775337  1.50882303  0.74565448  3.25781097
   0.88563849  2.98956473]
 [ 0.227084    2.00884581  0.83897142  0.36132641  8.29004923  0.55040858
   2.65572456  2.73458296]
 [ 1.57814792  3.83832285  0.15387272  0.81997581  1.92650884  1.42614468
   2.85944175  1.64725313]
 [ 2.13817323  0.96036837  0.37505493  0.89166258  4.23278146  2.93036454
   1.10876379  1.18543174]
 [ 6.93435091  2.00870283  4.01614472  1.9363563   2.338357    1.52163259
   2.355926    2.21737298]
 [ 0.18291793  2.56038344  4.0617246   0.68762892  5.09833436  1.18077518
   5.32689891 12.38548585]]
lamUz
[[1.76546972 1.66016519 1.94854326 1.98634876 1.4637077  1.61942522
  1.63664424 1.95685371]]
lamWs
[[5024.86590377 4384.13952281 47

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEEP_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CEEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.60757534 1.78704559 0.23546778 1.87628053 0.72417931 0.46499721
  0.33288647 0.30505453]
 [0.79657597 3.039805   5.86985816 0.92373993 0.27354535 1.65070551
  0.65488126 0.87394122]
 [3.64734116 3.35786482 2.98956473 1.36924754 2.02200378 4.28169678
  1.38755117 2.91629106]
 [0.29128105 0.89558707 0.64326967 2.77261545 1.82601667 3.28099886
  1.93722439 5.8441195 ]
 [2.77179147 4.62520996 7.47812446 6.25733452 0.05320537 1.69261752
  1.40452468 2.33411195]
 [2.16918005 3.54557904 0.86360889 2.59415601 1.3675051  0.89439412
  1.12129519 0.63948437]
 [4.43212912 0.68682066 3.22757026 0.84776745 0.73033436 3.32779647
  0.82571547 4.29117855]
 [0.29542328 0.70206978 3.79409429 1.30794064 2.46224417 4.53982148
  5.31622127 3.37627986]]
lamUz
[[1.87705789 1.80711584 1.58716541 1.76335469 1.54852777 1.64474799
  1.76746538 2.27134793]]
lamWs
[[4749.81201945 4896.92371354 4498.08495165 4982.67925017 4579.09383716
  4438.25308317 4394.434

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEEP_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CEEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.2372119  0.33478867 0.42262794 0.22275437 0.4387058  0.60464791
  0.38888244 0.83448388]
 [2.08928175 3.31011998 4.87875508 3.13292689 1.00755395 1.99984689
  1.46662535 1.59599401]
 [2.35625853 2.28764383 1.77734101 2.10562434 4.94466622 3.24104234
  4.48712784 4.00934005]
 [0.24038451 1.94197698 1.32196515 2.60301258 1.85511345 0.93901596
  8.33356715 1.59528807]
 [0.56911147 6.91045712 2.14579262 3.84161602 0.26320046 1.60444876
  2.33302847 1.34592519]
 [2.02859734 4.33717587 1.47368141 2.10862542 5.37533716 3.82986301
  1.64085585 2.64610348]
 [3.99650172 3.74390142 2.73216337 3.06154889 0.9359449  1.5292156
  1.41189235 1.78593565]
 [1.82730281 7.59571806 2.51765312 1.06245099 0.58564701 2.49318417
  3.0987388  6.26717564]]
lamUz
[[1.59615526 1.67712027 1.88791577 1.75553062 1.3533628  1.87857423
  1.75956098 2.05231109]]
lamWs
[[3923.23618184 4410.11819104 4096.11309358 5121.43133797 4362.65992566
  5198.41909533 4169.8959

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEEP_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CEEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.60918768 0.24840005 0.20619299 0.60342338 0.44851249 2.23967927
  0.60697106 0.77741103]
 [0.11849114 5.16334985 2.96205687 0.11792691 0.45822002 1.32473064
  2.01059127 2.80290932]
 [6.34824587 0.75883359 2.75067764 4.08415937 3.66855726 0.90839003
  2.76968035 0.49809818]
 [0.33587409 0.17435777 3.85753722 7.79536607 1.10156348 1.19175047
  1.01548002 2.80575995]
 [2.85178841 0.82147865 1.70642313 1.95684072 0.17866458 1.45718335
  0.69547962 1.82751036]
 [4.23040321 1.3117055  1.20629036 0.88629073 1.92370482 1.0074078
  3.13618826 1.77790763]
 [1.38408879 3.35901323 1.00740986 0.11120093 4.67952107 1.75777222
  1.24845293 2.60249735]
 [0.78325352 6.9489114  2.05437929 2.30000882 4.02022881 4.53216732
  0.23507722 0.14386986]]
lamUz
[[1.32012438 1.81929043 1.51342217 1.77299731 1.44511721 1.79475891
  1.3705465  1.95372891]]
lamWs
[[4362.65992566 4072.64049573 5023.93331439 4104.24303501 3920.78755505
  3919.26724725 6162.3965

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CEEP_multiz/multivariate_model_z_index10.pkl
Training complete for snapshot 10
Model saved at ../models/CEEP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Number of models loaded: 5 from: ../models/CEEP_multiz/
  Loaded 5 models for CEEP

Training CMP: Cluster Gas Metallicity
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[ 0.85450725  0.34421564  0.67385658  1.80360997  0.26450241  0.86143527
   1.1153857   0.36356708  0.29831389  0.26852547  0.42808131]
 [ 1.36794421 18.80247788  2.42591397  1.41124214  0.81205912  1.87015018
   3.55888224  6.87124119  2.96412364  2.45972539  2.42787387]
 [ 0.19110083  2.16382557  6.75459035  2.25597112  0.81616745  5.2716367
   2.24149794  0.18946984  2.45293197  0.46499778  8.72208089]
 [ 0.38772602  2.91366467  6.42401322  0.59361321  2.54056207  0.88906015
   0.54131461  3.34018785  1.88892745  1.97151642  0.97653891]
 [ 3.14128749  2.09160808  1.81631015  2.06235721  3.40417605  2.78377242
   0.74759676  1.09668485  2.42160516  2.89836063  0.17932089]
 [ 2.06603846  2.00707174  0.58392656  2.76797451  3.18332805  5.03101495
   2.9337091   2.03077973  3.02512936  1.40777712  2.84816599]
 [ 5.54612812  3.29694783  3.51185435  2.48608939  1.9710133   0.63345232
   6.53202555  1.83179802  0.58184257  2.21694895  0

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CMP_multiz/multivariate_model_z_index6.pkl
Training complete for snapshot 6
Model saved at ../models/CMP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.56449238 0.50787479 0.22291775 0.37355267 0.45030208 0.1393079
  0.42501705 0.4541997  0.22171926 0.66600275 1.25494698 0.11019727]
 [1.41785523 1.29615455 2.12272798 0.67003354 2.33280551 2.84031902
  3.05930446 0.60186098 2.43735508 3.91279667 2.63295213 1.10693751]
 [0.23229978 1.38385657 0.15020016 5.35755949 3.00159104 0.40561632
  0.31056662 1.85215298 0.21558804 1.91679381 1.29133704 2.52914999]
 [9.3472261  1.32648877 1.30167247 2.21838448 1.55450319 3.44312175
  2.06799146 1.41620045 0.28830246 0.20301402 0.37643843 1.16710489]
 [0.63632392 3.45939169 1.297777   1.57401782 2.40101236 0.76054407
  1.11367386 1.56602781 0.15064723 3.73758986 3.99570838 4.69903292]
 [1.21620753 9.77206942 0.11415898 2.72848394 1.78127759 2.16199085
  3.06983414 3.27923905 1.41504106 0.07302751 1.9372001  0.25531311]
 [2.4907177  2.78344948 0.05865586 4.88317605 3.22585201 0.99483
  2.40744138 5.64250641 1.52041128 1.43964124 0.92785403 0.78

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CMP_multiz/multivariate_model_z_index7.pkl
Training complete for snapshot 7
Model saved at ../models/CMP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.50524006 0.90825565 0.29591975 1.19286286 0.58222105 0.16252568
  0.34079324 0.61688783 0.18141913 1.53490818 0.36302974]
 [0.02972907 2.78832595 3.56899981 2.82681102 2.39278892 2.51211553
  0.39300203 3.5732033  5.41957717 2.5049648  2.86419088]
 [0.21926875 5.36024878 3.73301199 1.50209582 0.74075775 0.45889896
  2.78543032 4.31935294 2.29371457 3.27691547 1.74275022]
 [4.61613772 4.37125927 0.37355897 0.64634949 0.78122012 2.5051481
  1.71424047 2.77254704 0.22412677 2.90397772 0.32049515]
 [0.46671558 4.38105843 0.60719711 1.7381105  0.89938439 3.09158424
  1.10570184 0.82939874 2.953152   0.44942696 5.87783021]
 [0.06429873 7.1719478  0.4663578  0.12494535 0.87298578 1.3239264
  6.89722903 1.2688474  1.74041317 2.31740396 1.64525447]
 [1.77832377 2.52768902 1.71241688 2.05255814 0.0633831  1.28395933
  0.54379033 2.51075436 1.313762   3.13213797 3.32763116]
 [1.58686126 1.31846979 1.8369541  1.90969135 0.10763275 1.27726354

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CMP_multiz/multivariate_model_z_index8.pkl
Training complete for snapshot 8
Model saved at ../models/CMP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


MCMC sampling:   0%|          | 0/1000 [00:00<?, ?it/s]

Done with tune_step_size.
Selected step sizes:
betaU
[[0.12561119 0.189552   0.25985107 0.2033575  1.04227556 0.84643121
  0.31631562 1.36413752 0.29980023 0.38652776]
 [0.75479756 4.20860753 4.13579674 3.93935391 4.25724326 0.72521415
  0.05913118 3.31603095 1.60260406 2.07973245]
 [3.95189651 9.76953714 0.59660497 4.40931612 1.28434039 0.30955447
  1.2913631  5.14203008 0.20794141 0.77725904]
 [5.01722907 1.48910963 0.31108498 4.34268934 4.30010313 3.02674637
  5.8717948  1.80639819 1.92242837 1.04347843]
 [2.74011708 2.16694741 3.46575642 2.01527117 3.09530322 2.21185686
  1.76158251 1.99678129 2.7612738  0.49707151]
 [1.64163741 4.74111531 2.52624357 0.54301962 0.25094776 2.72750098
  1.59501306 4.98215108 0.40820232 0.26607846]
 [3.23224502 6.51807851 8.25314755 1.26003143 2.27421306 0.95417851
  0.53463419 4.9568081  0.33836868 1.23834722]
 [2.3381521  2.2259909  2.42952762 1.20744634 2.72069654 0.80111499
  0.07996591 1.64079478 2.71186289 1.44046232]]
lamUz
[[1.28725312 1.60295

Step size tuning:   0%|          | 0/50 [00:00<?, ?it/s]

Model saved to ../models/CMP_multiz/multivariate_model_z_index9.pkl
Training complete for snapshot 9
Model saved at ../models/CMP_multiz/
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
Starting tune_step_sizes...
Default step sizes:
betaU
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
lamUz
[[5. 5. 5. 5. 5. 5. 5. 5. 5.]]
lamWs
[[100. 100. 100. 100. 100. 100. 100. 100. 100.]]
lamWOs
[[100.]]


Step size tuning:  22%|██▏       | 11/50 [00:10<00:35,  1.09it/s]

## Validation at z=0 (all profiles)

In [ ]:
n_profiles = len(PROFILE_CONFIGS)
ncols = 4
nrows = (n_profiles + ncols - 1) // ncols

fig, axes = plt.subplots(nrows, ncols, figsize=(4*ncols, 3*nrows))
axes = axes.flatten()

for idx, (short_name, config) in enumerate(PROFILE_CONFIGS.items()):
    ax = axes[idx]
    model_list, data_list = profile_models[short_name]
    arr = profile_data[short_name]
    y_vals = arr[:, :, rad_cond]

    for t_idx in test_sim_indices[:3]:
        target = y_vals[t_idx, -1, :]  # z=0 (last snapshot)
        pred_mean, pred_quant = emulate(model_list[-1], params32[t_idx])
        ax.plot(y_ind_profiles, target, 'k-', alpha=0.5)
        ax.plot(y_ind_profiles, pred_mean[:, 0], 'r--', alpha=0.7)

    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_title(short_name)
    ax.set_xlabel(r'$r/R_{500c}$')

for idx in range(len(PROFILE_CONFIGS), len(axes)):
    axes[idx].set_visible(False)

plt.tight_layout()
plt.savefig('../plots/profiles_multiz_validation.png', bbox_inches='tight')

## Redshift interpolation test

In [ ]:
fig, axes = plt.subplots(2, 4, figsize=(16, 6))
axes = axes.flatten()

test_params = params32[test_sim_indices[0]]
z_grid = np.linspace(profile_z_all[-2], profile_z_all[1], 5)

for idx, (short_name, config) in enumerate(PROFILE_CONFIGS.items()):
    ax = axes[idx]
    model_list, data_list = profile_models[short_name]

    for z_target in z_grid:
        params_with_z = np.append(test_params, [z_target])[np.newaxis, :]
        pred_z, pred_z_err = emu_redshift(params_with_z, model_list, data_list, profile_z_all)
        ax.plot(y_ind_profiles, pred_z[:, 0], label=f'z={z_target:.2f}')

    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_title(short_name)
    ax.legend(fontsize=6)

plt.tight_layout()
plt.savefig('../plots/profiles_multiz_redshift_interp.png', bbox_inches='tight')